name: mobx_training
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3


dev_dependencies:
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/perfil.jpg
    - images/google_avatar.png


